### ISSUE TITLE
MetalLB 설치 에러 - 1.25 버전

### ISSUE THREAD

**Issue by junghoon2** [wikibook/kubepractice#1]
안녕하세요 저자 이정훈(제리)입니다.

1.24 버전에서는 책 가이드에 따라 MetalLB 0.12.1로 정상적으로 설치가 됩니다.
하지만 1.25(+1.26) 버전에서는 MetalLB 0.12.1로 설치가 안되고 깃헙 소스 코드의 MetalLB 0.13.7로 설치하면 됩니다.

헬름 파일로 MetalLB 설치하고 아래 YAML 파일을 추가로 적용해 주시면 됩니다. 

```
k apply -f IPAddressPool.yaml
k apply -f L2Advertisement.yaml 
```

**Comment by dinobei** [comment]
안녕하세요!
1.26 버전에서 설치 안되는 문제로 이슈 참고하였습니다.
1.13.7은 오타로 보이고, 0.13.7로 설치 완료하였습니다.

감사합니다!

**Comment by junghoon2** [comment]
> 안녕하세요! 1.26 버전에서 설치 안되는 문제로 이슈 참고하였습니다. 1.13.7은 오타로 보이고, 0.13.7로 설치 완료하였습니다.
> 
> 감사합니다!

확인 감사합니다. 
그리고 말씀하신대로 오타 수정하여 1.13.7 to 0.13.7 수정하였습니다.
