### ISSUE TITLE
[질문] 3개 VM의 VirtualBox 네트워킹 모드 문의

### ISSUE THREAD

**Issue by hyunghyo** [wikibook/kubepractice#2]
1. 도서를 구입하여 실습 환경을 구축 중인데 문의가 있어서 글을 드립니다.
2. 도서에서 구축한 실습 환경에서는 VM 네트워킹 모드가 어떤 방식을 이용하셨는지요?
   가. VM간 통신이 가능하려면 NAT Network, Bridge 모드가 아닐까 합니다만...
3. 저는 인터넷을 검색하다가 VM간 통신, VM과 호스트간 통신을 가능하게 하는 NAT와 Host-Only 네트워킹 모드 2가지를 함께 적용한 상태태입니다.

**Comment by junghoon2** [comment]
NAT NETWORK, Bridge 방식 2가지 사용 가능합니다. 저는 실습으로는 회사의 유휴 서버를 사용했는데 Bridge 방식으로 사용했습니다. Bridge 방식이 Node 네트워크 대역과 동일하여 사용이 편리합니다.

https://takudaddy.tistory.com/352
![image](https://user-images.githubusercontent.com/5566672/212539485-67874a70-a38e-441d-932b-3173ea51a314.png)

![image](https://user-images.githubusercontent.com/5566672/212539491-0d6ed93a-78ec-450b-b63f-add8cbc50181.png)
