### ISSUE TITLE
로키 헬름 차트 버전 4.8.0 업데이트

### ISSUE THREAD

**Issue by junghoon2** [wikibook/kubepractice#3]
안녕하세요 저자 이정훈입니다.

2023년 3월 현재 기준으로 로키 헬름 차트 파일(4.8.0)과 설치에 사용한 헬름 파일을 공유합니다.
해당 파일을 기준으로 설치하면 됩니다. (쿠버네티스 1.26.2 테스트 완료)

헬름 차트 파일
https://github.com/wikibook/kubepractice/tree/main/ch20/loki-4.8.0 

헬름 Value 파일
https://github.com/wikibook/kubepractice/blob/main/ch20/loki-4.8.0/my-values.yaml

**Comment by hacker-taso** [comment]
<img width="910" alt="스크린샷 2024-02-10 오후 10 20 17" src="https://github.com/wikibook/kubepractice/assets/8960692/c164ee36-c735-4b65-9472-411c01e8d320">
전 pvc가 요런 에러가 뜨면서 안되네요 😢 
쿠버네티스 v1.29.1 이고, m1맥북에서 vmware로 구성해서 실습중입니다

**Comment by hacker-taso** [comment]
```
kubectl patch sc openebs-hostpath -p \
  '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'
```
로 default storageclass를 지정해주면 되네요.

**Comment by junghoon2** [comment]
> ```
> kubectl patch sc openebs-hostpath -p \
>   '{"metadata": {"annotations": {"storageclass.kubernetes.io/is-default-class": "true"}}}'
> ```
> 
> 로 default storageclass를 지정해주면 되네요.

감사합니다.

혹은 loki에서 스토리지 클래스 이름을 직접 지정해도 됩니다.

default 스토리지 클래스를 지정하면 스토리지 클래스를 지정하지 않으면 자동으로 default 스토리지 클래스를 사용하게 됩니다.
