### ISSUE TITLE
OpenEBS 로컬 호스트패스 설치 에러

### ISSUE THREAD

**Issue by Shabet** [wikibook/kubepractice#4]
157페이지에 명시된 github URL이 변경된 것으로 보입니다. (아니면 오타일수도)

https://openebs.io/docs/user-guides/localpv-hostpath

책)
kubectl apply -f https://openebs.github.io/charts/open-ebs-operator-lite.yaml
kubectl apply -f https://openebs.github.io/charts/open-ebs-lite-sc.yaml

ref)
kubectl apply -f https://openebs.github.io/charts/openebs-operator-lite.yaml
kubectl apply -f https://openebs.github.io/charts/openebs-lite-sc.yaml

**Comment by junghoon2** [comment]
확인 감사합니다.

편집 과정에 줄바꿈이 있어 openebs과 open-ebs로 나누어진 것 같습니다.
