### ISSUE TITLE
설치오류이긴한데요

### ISSUE THREAD

**Issue by jinwoo-lee-github** [wikibook/kubepractice#5]
쭉쭉 진행되다가 요 빨간 메시지 나고 진행이 안되는데 왜이러는걸까요..

TASK [kubernetes/control-plane : Create kubeadm token for joining nodes with 24h expiration (default)] ***
fatal: [k3s-master]: FAILED! => {"attempts": 5, "changed": false, "cmd": ["/usr/local/bin/kubeadm", "--kubeconfig", "/etc/kubernetes/admin.conf", "token", "create"], "delta": "0:01:15.035961", "end": "2023-05-01 13:23:38.242963", "msg": "non-zero return code", "rc": 1, "start": "2023-05-01 13:22:23.207002", "stderr": "timed out waiting for the condition\nTo see the stack trace of this error execute with --v=5 or higher", "stderr_lines": ["timed out waiting for the condition", "To see the stack trace of this error execute with --v=5 or higher"], "stdout": "", "stdout_lines": []}
fatal: [k3s-node-1 -> k3s-master]: FAILED! => {"attempts": 5, "changed": false, "cmd": ["/usr/local/bin/kubeadm", "--kubeconfig", "/etc/kubernetes/admin.conf", "token", "create"], "delta": "0:01:15.049674", "end": "2023-05-01 13:23:38.289178", "msg": "non-zero return code", "rc": 1, "start": "2023-05-01 13:22:23.239504", "stderr": "timed out waiting for the condition\nTo see the stack trace of this error execute with --v=5 or higher", "stderr_lines": ["timed out waiting for the condition", "To see the stack trace of this error execute with --v=5 or higher"], "stdout": "", "stdout_lines": []}
fatal: [k3s-node-2 -> k3s-master]: FAILED! => {"attempts": 5, "changed": false, "cmd": ["/usr/local/bin/kubeadm", "--kubeconfig", "/etc/kubernetes/admin.conf", "token", "create"], "delta": "0:01:15.046024", "end": "2023-05-01 13:23:38.352254", "msg": "non-zero return code", "rc": 1, "start": "2023-05-01 13:22:23.306230", "stderr": "timed out waiting for the condition\nTo see the stack trace of this error execute with --v=5 or higher", "stderr_lines": ["timed out waiting for the condition", "To see the stack trace of this error execute with --v=5 or higher"], "stdout": "", "stdout_lines": []}

**Comment by junghoon2** [comment]
보여주신 에러로는 찾기가 어렵네요.

새로 업데이트한 아래 kubespray 소스로 설치해 보실 수 있을까요?

https://github.com/wikibook/kubepractice/tree/main/ch01/kubespray-v2.22.0
